name: Android CI

on: 
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 29
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: eskatos/gradle-command-action@v1
      with:
          wrapper-directory: src/android
          arguments: build
